import React, { useState, useEffect } from 'react';
import {
  Calendar,
  Clock,
  Video,
  FileText,
  Star,
  Printer,
  Download,
  CheckCircle2,
  XCircle,
  AlertCircle,
  Building2,
  ExternalLink,
  ChevronRight,
  User,
  HeartPulse,
} from 'lucide-react';
import api from '../services/api';
import { useAuth } from '../context/AuthContext';
import PrescriptionTemplate from '../components/PrescriptionTemplate';

const PatientDashboard = () => {
  const { user } = useAuth();
  const [activeTab, setActiveTab] = useState('appointments'); // 'appointments' | 'records'
  const [appointments, setAppointments] = useState([]);
  const [prescriptions, setPrescriptions] = useState([]);
  const [loading, setLoading] = useState(true);

  // Modals state
  const [selectedPrescription, setSelectedPrescription] = useState(null);
  const [reviewModalDoctor, setReviewModalDoctor] = useState(null);
  const [ratingVal, setRatingVal] = useState(5);
  const [commentVal, setCommentVal] = useState('');
  const [reviewSubmitting, setReviewSubmitting] = useState(false);
  const [reviewSuccessMsg, setReviewSuccessMsg] = useState('');

  useEffect(() => {
    fetchDashboardData();
  }, []);

  const fetchDashboardData = async () => {
    try {
      setLoading(true);
      const [apptRes, rxRes] = await Promise.all([
        api.get('/appointments/my'),
        api.get('/prescriptions/my-prescriptions'),
      ]);
      setAppointments(apptRes.data);
      setPrescriptions(rxRes.data);
    } catch (err) {
      console.error('Error fetching dashboard data:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleCancelAppointment = async (apptId) => {
    if (!window.confirm('Are you sure you want to cancel this appointment?')) return;
    try {
      await api.patch(`/appointments/${apptId}/status`, { status: 'cancelled' });
      fetchDashboardData();
    } catch (err) {
      alert(err.response?.data?.message || 'Error cancelling appointment');
    }
  };

  const handleOpenPrescription = async (appointmentId) => {
    try {
      const res = await api.get(`/prescriptions/appointment/${appointmentId}`);
      setSelectedPrescription(res.data);
    } catch (err) {
      alert('Prescription not found or not yet generated by doctor.');
    }
  };

  const handleReviewSubmit = async (e) => {
    e.preventDefault();
    if (!reviewModalDoctor) return;

    try {
      setReviewSubmitting(true);
      await api.post('/reviews', {
        doctorId: reviewModalDoctor._id,
        rating: ratingVal,
        comment: commentVal,
      });
      setReviewSuccessMsg('Thank you! Your review has been recorded.');
      setTimeout(() => {
        setReviewModalDoctor(null);
        setReviewSuccessMsg('');
        setCommentVal('');
      }, 1500);
    } catch (err) {
      alert(err.response?.data?.message || 'Failed to submit review');
    } finally {
      setReviewSubmitting(false);
    }
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 text-left">
      {/* Patient Welcome Banner */}
      <div className="bg-gradient-to-r from-blue-600 via-blue-700 to-indigo-800 rounded-3xl p-6 sm:p-8 text-white shadow-xl shadow-blue-900/10 mb-8 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-6">
        <div className="space-y-1">
          <span className="px-3 py-1 bg-white/20 text-xs font-semibold rounded-full uppercase tracking-wider inline-block">
            Patient Portal
          </span>
          <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight">Welcome, {user?.name}!</h1>
          <p className="text-xs sm:text-sm text-blue-100">
            {user?.email} • Track your scheduled visits, attend video consultations, and review digital prescriptions.
          </p>
        </div>

        <div className="flex items-center gap-3 bg-white/10 backdrop-blur-md p-4 rounded-2xl border border-white/15 shrink-0">
          <div className="text-center px-2">
            <div className="text-2xl font-black">{appointments.length}</div>
            <div className="text-[11px] text-blue-100">Appointments</div>
          </div>
          <div className="w-px h-8 bg-white/20" />
          <div className="text-center px-2">
            <div className="text-2xl font-black text-cyan-300">{prescriptions.length}</div>
            <div className="text-[11px] text-blue-100">Prescriptions</div>
          </div>
        </div>
      </div>

      {/* Navigation Tabs */}
      <div className="flex border-b border-slate-200 mb-8 gap-4">
        <button
          onClick={() => setActiveTab('appointments')}
          className={`pb-3 text-sm font-bold flex items-center gap-2 border-b-2 transition-all ${
            activeTab === 'appointments'
              ? 'border-blue-600 text-blue-600'
              : 'border-transparent text-slate-500 hover:text-slate-700'
          }`}
        >
          <Calendar className="w-4 h-4" />
          My Appointments ({appointments.length})
        </button>

        <button
          onClick={() => setActiveTab('records')}
          className={`pb-3 text-sm font-bold flex items-center gap-2 border-b-2 transition-all ${
            activeTab === 'records'
              ? 'border-blue-600 text-blue-600'
              : 'border-transparent text-slate-500 hover:text-slate-700'
          }`}
        >
          <FileText className="w-4 h-4" />
          Digital Health Records ({prescriptions.length})
        </button>
      </div>

      {/* TAB 1: APPOINTMENTS */}
      {activeTab === 'appointments' && (
        <div>
          {loading ? (
            <div className="py-12 text-center text-slate-500 text-sm">Loading your consultations...</div>
          ) : appointments.length === 0 ? (
            <div className="p-12 text-center bg-white rounded-3xl border border-slate-200 max-w-md mx-auto">
              <Calendar className="w-12 h-12 text-slate-300 mx-auto mb-3" />
              <h3 className="font-bold text-slate-800 text-base">No Appointments Yet</h3>
              <p className="text-xs text-slate-500 mt-1">You have not booked any appointments so far.</p>
              <a
                href="/doctors"
                className="mt-4 inline-block px-5 py-2.5 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold rounded-xl shadow-md"
              >
                Find and Book a Doctor
              </a>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {appointments.map((appt) => {
                const doc = appt.doctor;
                const docUser = doc?.user;

                return (
                  <div
                    key={appt._id}
                    className="bg-white rounded-3xl border border-slate-200 p-6 flex flex-col justify-between shadow-sm hover:shadow-md transition-all space-y-4"
                  >
                    <div>
                      {/* Status header */}
                      <div className="flex items-center justify-between mb-3">
                        <span
                          className={`px-2.5 py-1 text-[11px] font-bold uppercase rounded-lg tracking-wider ${
                            appt.status === 'completed'
                              ? 'bg-emerald-50 text-emerald-700 border border-emerald-200'
                              : appt.status === 'confirmed'
                              ? 'bg-blue-50 text-blue-700 border border-blue-200'
                              : 'bg-red-50 text-red-700 border border-red-200'
                          }`}
                        >
                          {appt.status}
                        </span>

                        <div className="flex items-center gap-1 text-xs text-slate-500">
                          {appt.consultationType === 'video' ? (
                            <span className="inline-flex items-center gap-1 text-cyan-700 font-semibold bg-cyan-50 px-2 py-0.5 rounded-md">
                              <Video className="w-3 h-3 text-cyan-600" /> Video Call
                            </span>
                          ) : (
                            <span className="inline-flex items-center gap-1 text-slate-600 font-medium bg-slate-100 px-2 py-0.5 rounded-md">
                              <Building2 className="w-3 h-3 text-slate-500" /> In-Clinic
                            </span>
                          )}
                        </div>
                      </div>

                      {/* Doctor info */}
                      <h3 className="font-bold text-slate-900 text-base">{docUser?.name || 'Doctor'}</h3>
                      <p className="text-xs text-blue-600 font-semibold">{doc?.specialization}</p>

                      {/* Date & Time */}
                      <div className="mt-4 p-3 bg-slate-50 rounded-2xl space-y-1.5 text-xs text-slate-600 border border-slate-100">
                        <div className="flex items-center gap-2">
                          <Calendar className="w-4 h-4 text-slate-400" />
                          <span className="font-semibold">{appt.date}</span>
                        </div>
                        <div className="flex items-center gap-2">
                          <Clock className="w-4 h-4 text-slate-400" />
                          <span>{appt.timeSlot}</span>
                        </div>
                      </div>

                      {/* Symptoms */}
                      {appt.symptoms && (
                        <div className="mt-3 text-xs text-slate-500">
                          <span className="font-semibold text-slate-700">Reason: </span>
                          <span className="italic">{appt.symptoms}</span>
                        </div>
                      )}

                      {/* Payment Status Badge */}
                      <div className="mt-3 flex items-center justify-between text-[11px] bg-slate-50 p-2.5 rounded-xl border border-slate-100">
                        <span className="text-slate-500 font-semibold">Payment:</span>
                        <div className="flex items-center gap-1.5">
                          <span className={`font-bold px-2 py-0.5 rounded-md uppercase tracking-wider text-[10px] ${
                            appt.paymentStatus === 'paid'
                              ? 'bg-emerald-50 text-emerald-700 border border-emerald-200'
                              : 'bg-amber-50 text-amber-700 border border-amber-200'
                          }`}>
                            {appt.paymentStatus === 'paid'
                              ? `Paid (₹${appt.amount || doc?.fees || 500} • ${appt.paymentMethod || 'UPI'})`
                              : `Pay at Clinic (₹${appt.amount || doc?.fees || 500})`}
                          </span>
                        </div>
                      </div>
                    </div>

                    {/* Actions */}
                    <div className="pt-3 border-t border-slate-100 space-y-2">
                      {/* Video call button */}
                      {appt.consultationType === 'video' && appt.status === 'confirmed' && appt.meetingLink && (
                        <a
                          href={`${appt.meetingLink}#userInfo.displayName="${encodeURIComponent(user?.name || 'Patient')}"`}
                          target="_blank"
                          rel="noreferrer"
                          className="w-full py-2.5 bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-700 hover:to-blue-700 text-white rounded-xl text-xs font-bold flex items-center justify-center gap-2 shadow-md shadow-blue-500/20"
                        >
                          <Video className="w-4 h-4" />
                          Join Video Consultation Room
                          <ExternalLink className="w-3.5 h-3.5" />
                        </a>
                      )}

                      {/* View Prescription */}
                      {appt.status === 'completed' && (
                        <button
                          onClick={() => handleOpenPrescription(appt._id)}
                          className="w-full py-2.5 bg-emerald-50 hover:bg-emerald-100 text-emerald-700 border border-emerald-200 rounded-xl text-xs font-bold flex items-center justify-center gap-1.5 transition-colors"
                        >
                          <FileText className="w-4 h-4" />
                          View Digital Prescription
                        </button>
                      )}

                      {/* Rate Doctor button */}
                      {appt.status === 'completed' && doc && (
                        <button
                          onClick={() => setReviewModalDoctor(doc)}
                          className="w-full py-2 bg-amber-50 hover:bg-amber-100 text-amber-700 rounded-xl text-xs font-semibold flex items-center justify-center gap-1 transition-colors"
                        >
                          <Star className="w-3.5 h-3.5 fill-amber-400 text-amber-400" />
                          Rate Doctor Experience
                        </button>
                      )}

                      {/* Cancel Button */}
                      {appt.status === 'confirmed' && (
                        <button
                          onClick={() => handleCancelAppointment(appt._id)}
                          className="w-full py-2 text-xs text-red-600 hover:bg-red-50 rounded-xl font-medium transition-colors"
                        >
                          Cancel Appointment
                        </button>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      )}

      {/* TAB 2: DIGITAL HEALTH RECORDS / TIMELINE */}
      {activeTab === 'records' && (
        <div className="space-y-6">
          {prescriptions.length === 0 ? (
            <div className="p-12 text-center bg-white rounded-3xl border border-slate-200 max-w-md mx-auto">
              <FileText className="w-12 h-12 text-slate-300 mx-auto mb-3" />
              <h3 className="font-bold text-slate-800 text-base">No Health Records Yet</h3>
              <p className="text-xs text-slate-500 mt-1">
                Once a doctor conducts your consultation and writes a prescription, it will appear here permanently.
              </p>
            </div>
          ) : (
            <div className="space-y-6">
              {prescriptions.map((rx) => (
                <div
                  key={rx._id}
                  className="bg-white rounded-3xl border border-slate-200 p-6 md:p-8 shadow-sm hover:shadow-md transition-all space-y-4"
                >
                  <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pb-4 border-b border-slate-100">
                    <div>
                      <span className="text-xs font-bold uppercase text-emerald-700 bg-emerald-50 px-2.5 py-1 rounded-lg">
                        Official Medical Record
                      </span>
                      <h3 className="text-xl font-bold text-slate-900 mt-2">
                        Prescription by {rx.doctor?.user?.name || 'Doctor'}
                      </h3>
                      <p className="text-xs text-slate-500">
                        {rx.doctor?.specialization} • Date: {new Date(rx.createdAt).toLocaleDateString()}
                      </p>
                    </div>

                    <button
                      onClick={() => setSelectedPrescription(rx)}
                      className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold rounded-xl flex items-center gap-1.5 shadow-sm"
                    >
                      <Printer className="w-4 h-4" />
                      Print / Download PDF View
                    </button>
                  </div>

                  {/* Diagnosis */}
                  <div className="bg-slate-50 p-4 rounded-2xl">
                    <span className="text-xs font-bold uppercase tracking-wider text-slate-500 block mb-1">
                      Clinical Diagnosis:
                    </span>
                    <p className="text-sm font-bold text-slate-900">{rx.diagnosis}</p>
                  </div>

                  {/* Medicines table */}
                  <div>
                    <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
                      Prescribed Medications:
                    </h4>
                    <div className="overflow-x-auto">
                      <table className="w-full text-left text-xs border border-slate-200 rounded-xl overflow-hidden">
                        <thead className="bg-slate-100 text-slate-700 font-bold uppercase text-[10px]">
                          <tr>
                            <th className="p-3">Medicine Name</th>
                            <th className="p-3">Dosage</th>
                            <th className="p-3">Frequency</th>
                            <th className="p-3">Duration</th>
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-100">
                          {rx.medicines?.map((med, idx) => (
                            <tr key={idx} className="hover:bg-slate-50">
                              <td className="p-3 font-bold text-slate-900">{med.name}</td>
                              <td className="p-3 text-slate-600">{med.dosage}</td>
                              <td className="p-3 text-slate-600">{med.frequency}</td>
                              <td className="p-3 text-slate-600">{med.duration}</td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  </div>

                  {/* Advice & Follow Up */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2 text-xs">
                    {rx.instructions && (
                      <div className="p-3 bg-blue-50/60 rounded-xl border border-blue-100">
                        <span className="font-bold text-blue-900 block mb-0.5">Doctor's Advice:</span>
                        <p className="text-blue-800">{rx.instructions}</p>
                      </div>
                    )}
                    {rx.followUpDate && (
                      <div className="p-3 bg-amber-50/60 rounded-xl border border-amber-100">
                        <span className="font-bold text-amber-900 block mb-0.5">Follow-Up Recommended:</span>
                        <p className="text-amber-800">{rx.followUpDate}</p>
                      </div>
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* MODAL 1: EXACT OFFICIAL MEDCONNECT PRESCRIPTION TEMPLATE */}
      {selectedPrescription && (
        <PrescriptionTemplate
          prescription={selectedPrescription}
          onClose={() => setSelectedPrescription(null)}
        />
      )}

      {/* MODAL 2: WRITE DOCTOR REVIEW */}
      {reviewModalDoctor && (
        <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-white w-full max-w-md rounded-3xl shadow-2xl p-6 space-y-4 text-left">
            <div className="flex items-center justify-between pb-3 border-b border-slate-100">
              <h3 className="font-bold text-slate-900 text-base">Rate Your Doctor</h3>
              <button
                onClick={() => setReviewModalDoctor(null)}
                className="text-slate-400 hover:text-slate-600 text-sm font-bold"
              >
                ✕
              </button>
            </div>

            {reviewSuccessMsg ? (
              <div className="p-4 bg-emerald-50 text-emerald-800 text-xs font-bold rounded-xl text-center">
                {reviewSuccessMsg}
              </div>
            ) : (
              <form onSubmit={handleReviewSubmit} className="space-y-4">
                <div>
                  <span className="text-xs text-slate-500">Doctor:</span>
                  <div className="font-bold text-slate-800 text-sm">{reviewModalDoctor.user?.name}</div>
                  <div className="text-xs text-blue-600">{reviewModalDoctor.specialization}</div>
                </div>

                {/* Rating selection */}
                <div>
                  <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1">
                    Rating (1 - 5 Stars)
                  </label>
                  <div className="flex items-center gap-2">
                    {[1, 2, 3, 4, 5].map((num) => (
                      <button
                        type="button"
                        key={num}
                        onClick={() => setRatingVal(num)}
                        className="p-1 text-2xl focus:outline-none"
                      >
                        <Star
                          className={`w-7 h-7 transition-colors ${
                            num <= ratingVal
                              ? 'text-amber-400 fill-amber-400'
                              : 'text-slate-200 hover:text-slate-300'
                          }`}
                        />
                      </button>
                    ))}
                    <span className="text-sm font-bold text-slate-700 ml-2">{ratingVal} / 5</span>
                  </div>
                </div>

                {/* Comment */}
                <div>
                  <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1">
                    Your Feedback
                  </label>
                  <textarea
                    rows={3}
                    value={commentVal}
                    onChange={(e) => setCommentVal(e.target.value)}
                    placeholder="Share your consultation experience, diagnosis clarity, punctuality..."
                    className="w-full p-3 text-xs bg-slate-50 border border-slate-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500/20"
                  />
                </div>

                <button
                  type="submit"
                  disabled={reviewSubmitting}
                  className="w-full py-3 bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs rounded-xl shadow-md transition-all"
                >
                  {reviewSubmitting ? 'Submitting...' : 'Post Review'}
                </button>
              </form>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

export default PatientDashboard;
